-- Create public.users table (admin accounts)
create table if not exists public.users (
  id text primary key default gen_random_uuid()::text,
  email text unique,
  first_name text,
  last_name text,
  profile_image_url text,
  is_admin boolean default false,
  created_at timestamp default now(),
  updated_at timestamp default now()
);

-- Add missing columns to blog_posts (title, slug, content, created_at)
alter table public.blog_posts
  add column if not exists title text,
  add column if not exists slug text,
  add column if not exists content text,
  add column if not exists created_at timestamp default now();

-- Create unique index on blog_posts.slug if not exists
create unique index if not exists blog_posts_slug_unique
  on public.blog_posts (slug)
  where slug is not null;

-- Create blog_generation_jobs table
create table if not exists public.blog_generation_jobs (
  id integer generated by default as identity primary key,
  post_id integer not null references public.blog_posts(id) on delete cascade,
  status text not null default 'pending',
  scheduled_at timestamp,
  started_at timestamp default now(),
  completed_at timestamp,
  error_message text,
  published_post_id integer references public.blog_posts(id),
  attempts integer default 1,
  locked_at timestamp,
  locked_by text,
  config jsonb default '{}'::jsonb,
  created_at timestamp default now(),
  updated_at timestamp default now()
);
