-- Add blog_settings table for automation configuration
create table if not exists public.blog_settings (
  id integer generated by default as identity primary key,
  enabled boolean default false not null,
  posts_per_day integer default 1 not null,
  last_run_at timestamp,
  seo_keywords text default '',
  prompt_style text default '',
  enable_trend_analysis boolean default true not null,
  updated_at timestamp default now()
);

-- Add blog_post_services junction table if not exists
create table if not exists public.blog_post_services (
  id integer generated by default as identity primary key,
  blog_post_id integer not null references public.blog_posts(id) on delete cascade,
  service_id integer not null references public.services(id) on delete cascade,
  created_at timestamp default now()
);

-- Create unique constraint to prevent duplicate service associations
create unique index if not exists blog_post_services_unique
  on public.blog_post_services (blog_post_id, service_id);

-- Add comment for documentation
comment on table public.blog_settings is 'Blog automation settings singleton table';
comment on table public.blog_post_services is 'Junction table linking blog posts to services';
