create table if not exists public.company_settings (
  id integer generated by default as identity primary key
);

create table if not exists public.chat_settings (
  id integer generated by default as identity primary key
);

create table if not exists public.blog_posts (
  id integer generated by default as identity primary key
);

alter table public.services
  add column if not exists is_archived boolean default false,
  add column if not exists show_on_landing boolean default true,
  add column if not exists pricing_type text default 'fixed_item',
  add column if not exists base_price numeric(10,2),
  add column if not exists price_per_unit numeric(10,2),
  add column if not exists minimum_price numeric(10,2),
  add column if not exists area_sizes jsonb;

alter table public.chat_settings
  add column if not exists enabled boolean default false,
  add column if not exists agent_name text default 'Assistant',
  add column if not exists agent_avatar_url text default '',
  add column if not exists active_provider text default 'openai',
  add column if not exists avg_response_time text default '',
  add column if not exists language_selector_enabled boolean default false,
  add column if not exists default_language text default 'en',
  add column if not exists system_prompt text default 'You are our helpful chat assistant. Provide concise, friendly answers. Use the provided tools to fetch services, details, and availability. Do not guess prices or availability; always use tool data when relevant. If booking is requested, gather details and direct the user to the booking page at /booking.',
  add column if not exists welcome_message text default 'Hi! How can I help you today?',
  add column if not exists calendar_provider text default 'gohighlevel',
  add column if not exists calendar_id text default '',
  add column if not exists calendar_staff jsonb default '[]'::jsonb,
  add column if not exists intake_objectives jsonb default '[]'::jsonb,
  add column if not exists excluded_url_rules jsonb default '[]'::jsonb,
  add column if not exists use_knowledge_base boolean default true,
  add column if not exists use_faqs boolean default true,
  add column if not exists show_in_prod boolean default false,
  add column if not exists updated_at timestamp default now();

alter table public.company_settings
  add column if not exists company_name text default '',
  add column if not exists industry text default '',
  add column if not exists company_email text default '',
  add column if not exists company_phone text default '',
  add column if not exists company_address text default '',
  add column if not exists working_hours_start text default '08:00',
  add column if not exists working_hours_end text default '18:00',
  add column if not exists logo_main text default '',
  add column if not exists logo_dark text default '',
  add column if not exists logo_icon text default '',
  add column if not exists sections_order text[] default array[]::text[],
  add column if not exists social_links jsonb default '[]'::jsonb,
  add column if not exists map_embed_url text default '',
  add column if not exists hero_title text default '',
  add column if not exists hero_subtitle text default '',
  add column if not exists hero_image_url text default '',
  add column if not exists cta_text text default 'Book Now',
  add column if not exists time_format text default '12h',
  add column if not exists time_zone text default 'America/New_York',
  add column if not exists business_hours jsonb default $${
    "monday": { "isOpen": true, "start": "08:00", "end": "18:00" },
    "tuesday": { "isOpen": true, "start": "08:00", "end": "18:00" },
    "wednesday": { "isOpen": true, "start": "08:00", "end": "18:00" },
    "thursday": { "isOpen": true, "start": "08:00", "end": "18:00" },
    "friday": { "isOpen": true, "start": "08:00", "end": "18:00" },
    "saturday": { "isOpen": false, "start": "09:00", "end": "14:00" },
    "sunday": { "isOpen": false, "start": "09:00", "end": "14:00" }
  }$$::jsonb,
  add column if not exists minimum_booking_value numeric(10,2) default 0,
  add column if not exists seo_title text default '',
  add column if not exists seo_description text default '',
  add column if not exists og_image text default '',
  add column if not exists seo_keywords text default '',
  add column if not exists seo_author text default '',
  add column if not exists seo_canonical_url text default '',
  add column if not exists seo_robots_tag text default 'index, follow',
  add column if not exists og_type text default 'website',
  add column if not exists og_site_name text default '',
  add column if not exists twitter_card text default 'summary_large_image',
  add column if not exists twitter_site text default '',
  add column if not exists twitter_creator text default '',
  add column if not exists schema_local_business jsonb default '{}'::jsonb,
  add column if not exists gtm_container_id text default '',
  add column if not exists ga4_measurement_id text default '',
  add column if not exists facebook_pixel_id text default '',
  add column if not exists gtm_enabled boolean default false,
  add column if not exists ga4_enabled boolean default false,
  add column if not exists facebook_pixel_enabled boolean default false,
  add column if not exists homepage_content jsonb default '{}'::jsonb;

alter table public.blog_posts
  add column if not exists excerpt text,
  add column if not exists meta_description text,
  add column if not exists focus_keyword text,
  add column if not exists tags text,
  add column if not exists feature_image_url text,
  add column if not exists status text default 'draft',
  add column if not exists author_name text default 'Admin',
  add column if not exists published_at timestamp,
  add column if not exists updated_at timestamp default now();
